Task dev 7
SiarheySkuratovich/EPAM pull request #11
Opened 2017-07-12 19:07 UTC by SiarheySkuratovich

2017-07-15 12:46 UTC, AlexanderSoroka requested changes
There is must be class fro each triangle type

2017-07-15 12:46 UTC, AlexanderSoroka commented on SideReading.java
> +   * Gets sides from command line and writes to array.
Not from command line - from console

2017-07-15 12:46 UTC, AlexanderSoroka commented on Triangle.java
> +    SideReading getting = new SideReading();
Single responsibility violation, class Triangle must not read sides in any way - pass sides as constructor arguments

2017-07-15 12:46 UTC, AlexanderSoroka commented on Triangle.java
> +    } else if (sides[0] == sides[1] || sides[1] == sides[2] || sides[0] == sides[2]) {
All these checks must be implemented in separate classes

2017-07-16 14:02 UTC, SiarheySkuratovich commented on Triangle.java
> +    } else if (sides[0] == sides[1] || sides[1] == sides[2] || sides[0] == sides[2]) {
@AlexanderSoroka exactly classes or i can leave as methods of Triangle class?

2017-07-18 12:07 UTC, AlexanderSoroka requested changes
For each triangle type you must have separate

2017-07-18 12:07 UTC, AlexanderSoroka commented on SideReading.java
> +  public double[] readSide() {
Why readSide (one side) but return array (many sides)?

2017-07-18 12:07 UTC, AlexanderSoroka commented on SideReading.java
> +   * Gets trangle sides from console and returns them as array.
javadoc violation

2017-07-18 12:07 UTC, AlexanderSoroka commented on Triangle.java
> +    sides = gottenSides;
Missed validation

2017-07-20 18:30 UTC, AlexanderSoroka requested changes
For each triangle type you must have separate
Hide outdated

2017-07-20 18:30 UTC, AlexanderSoroka commented on Triangle.java
> +    if(sides[0] == sides[1] && sides[1] == sides[2]) {
Return boolean value instead using if

2017-09-29 18:32 UTC, closed without merging