DEV-1
SiarheySkuratovich/EPAM pull request #2
Opened 2017-06-20 17:48 UTC by SiarheySkuratovich

2017-06-20 17:57 UTC, AlexanderSoroka requested changes

2017-06-20 17:57 UTC, AlexanderSoroka commented on Dev_1.java
> +    public static void main(String[] args){
codestyle violation

2017-06-20 17:57 UTC, AlexanderSoroka commented on Dev_1.java
> +        int temp;
uninitialized local variable

2017-06-20 17:57 UTC, AlexanderSoroka commented on Dev_1.java
> +        for(int i = 0; i <= 100; i++) {
codestyle violation

2017-06-20 17:57 UTC, AlexanderSoroka commented on Dev_1.java
> +            }
codestyle violation

2017-06-20 17:57 UTC, AlexanderSoroka commented on Dev_1.java
> +                temp = i / 3;
you don't actually need this temp variable

2017-06-20 18:26 UTC, SiarheySkuratovich commented on Dev_1.java
> +    public static void main(String[] args){
Can you tell me exactly what is wrong?

2017-06-20 18:27 UTC, SiarheySkuratovich commented on Dev_1.java
> +        int temp;
Is it unacceptable?

2017-06-20 18:29 UTC, SiarheySkuratovich commented on Dev_1.java
> +        for(int i = 0; i <= 100; i++) {
it's relly hard to find the mistake through the whole style document. Pleeease, give a hint

2017-06-20 18:30 UTC, SiarheySkuratovich commented on Dev_1.java
> +            }
Similarly

2017-06-21 14:56 UTC, AlexanderSoroka requested changes

2017-06-21 14:56 UTC, AlexanderSoroka commented on Dev_1.java
> +    public static void main(String[] args) {
codestyle violation (4.2)

2017-06-21 15:26 UTC, merged